spring:
  application:
    name: t1-academy-aop
  kafka:
    bootstrap-servers: localhost:9092
    topic: ${KAFKA_TOPIC}
    consumer:
      group-id: t1-academy-aop
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    from: ${MAIL_FROM}
    password: ${MAIL_PASSWORD}
    auth: true
    startls:
      enabled: true
      required: true
    ssl:
      enabled: true
    default-encoding: UTF-8
